### PR TITLE
Prepare package for Atom 1.0

### PR DESCRIPTION
**Pull request by jasonrudolph**
Prior to this pull request, Atom reports the following deprecations for the move-panes package:

screen shot 2015-05-22 at 3 58 23 pm

screen shot 2015-05-22 at 3 58 35 pm

This pull request resolves all of those deprecations.

### CODE REVIEW

**Comment by JustinAiken** [comment]
:+1:

**Comment by DominicBarnard** [comment]
:+1:

**Comment by santip** [comment]
released as 0.2.0

**Comment by JustinAiken** [comment]
Thanks @santip ! :beer:

**Pull request merged**
